#
# Copyright (c) 2019-2021 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#

name: Update Checker

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_URL1: https://github.com/coolsnowwolf/luci
  REPO_URL2: https://github.com/coolsnowwolf/packages
  REPO_URL3: https://github.com/fw876/helloworld
  REPO_URL4: https://github.com/iwrt/luci-app-ikoolproxy
  REPO_BRANCH: master
  REPO_BRANCH2: main
  
on:
  workflow_dispatch:
  schedule:
    - cron: 0 7/12 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Get Commit Hash
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
        git clone --depth 1 $REPO_URL1 -b $REPO_BRANCH .1
        git clone --depth 1 $REPO_URL2 -b $REPO_BRANCH .2
        git clone --depth 1 $REPO_URL3 -b $REPO_BRANCH .3
        git clone --depth 1 $REPO_URL4 -b $REPO_BRANCH2 .4
        echo "::set-output name=commitHash::$(git rev-parse HEAD)"

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v2
      with:
        path: .commitHash
        path1: .1commitHash
        path2: .2commitHash
        path3: .3commitHash
        path4: .4commitHash
        path5: .5commitHash
        key: HEAD-${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: Source Code Update
